### ISSUE TITLE
generic systems and thread-local systems have the same code snippet

### ISSUE THREAD

**Issue by cdaringe** [alice-i-cecile/understanding-bevy#10]
# Problem

https://alice-i-cecile.github.io/understanding-bevy/ecs/systems-queries.html

```
// Thread local system
use bevy::prelude::*;

fn main() {
    App::build().add_plugins(DefaultPlugins).run()
}

```

my guess is ^^ probably is incorrect, as it matches the prior snippet

**Comment by alice-i-cecile** [comment]
This is just placeholder code for now <3
